---
name: "Deploy Resources"

# Trigger when commits are pushed to the master branch

on:
  push:
    branches:
      - master

env:

  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_CFN_BUCKET: <<some delivery bucket>>
  AWS_BUCKET_PREFIX: <<bucket prefix>>
  AWS_DEFAULT_REGION: us-east-1
  AWS_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
  CFN_DIR: cloudformation

jobs:
  Deploy:
    name: Deploy Resources
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        run: |
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}
          export AWS_ROLE_ARN=${{ env.AWS_ROLE_ARN }}

          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Deploy/Update Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: bucket-effectual-mcm
          template: cloudformation/<<SomeTemplateInDir>>.yml
          no-fail-on-empty-changeset: "1"