name: Read Environment Workflow

on: [workflow_dispatch]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ROLE_ARN: ${{ secrets.READ_ROLE_ARN }}

jobs:
  Read-Buckets:
    name: Read Environment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        run: |
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION}}
          export AWS_ROLE_ARN=${{ env.AWS_ROLE_ARN }}

          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Read Ross Bucket
        if: github.ref == 'refs/heads/initial'
        run: |
          aws s3 ls s3://effectual-ross-sandbox

      - name: Read CFN Bucket
        if: github.ref != 'refs/heads/initial'
        run: |
          aws s3 ls s3://cf-templates-vjbsi5rfowxo-us-east-2